import { jsPDF } from "jspdf";
import JSZip from "jszip";
import { api } from "../api";

// Standard PDF fonts have no ₹ glyph, so use "Rs." in generated files.
const rs = (n: number) => "Rs. " + Number(n ?? 0).toFixed(2);
const clean = (s: string) => (s || "").replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 28);

interface EodItem { name: string; qty: number; unitPrice: number; lineTotal: number; modifiers: string[] }
interface EodOrder {
  number: number; createdAt: string; subtotal: number; discount: number; tax: number; total: number;
  tender: string | null; paid: boolean; customerName: string | null;
  customer: { phone: string } | null; cashier: { name: string } | null; items: EodItem[];
  payment: { method: string; change: number } | null;
}
interface EodData {
  date: string; storeName: string; taxRate: number;
  summary: {
    orderCount: number; sales: number; tax: number; discount: number;
    byMethod: Record<string, number>; topItems: { name: string; qty: number; revenue: number }[];
  };
  orders: EodOrder[];
}

function invoicePdf(o: EodOrder, storeName: string): Blob {
  const doc = new jsPDF({ unit: "mm", format: [80, 200] });
  let y = 8;
  const line = (t: string, size = 8, bold = false) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.text(t, 4, y);
    y += size * 0.5 + 1.5;
  };
  const row = (l: string, r: string, size = 8, bold = false) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.text(l, 4, y);
    doc.text(r, 76, y, { align: "right" });
    y += size * 0.5 + 1.5;
  };
  const dt = new Date(o.createdAt);
  line(storeName, 11, true);
  line("TAX INVOICE", 7);
  line(`Bill #${o.number}   ${dt.toLocaleDateString()} ${dt.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}`, 7);
  if (o.customerName || o.customer?.phone) line(`Customer: ${o.customerName ?? ""} ${o.customer?.phone ?? ""}`.trim(), 7);
  y += 1;
  doc.line(4, y, 76, y); y += 3;
  for (const it of o.items) {
    row(`${it.qty} x ${it.name}`.slice(0, 34), rs(it.lineTotal), 7);
    if (it.modifiers?.length) line("  + " + it.modifiers.join(", "), 6);
  }
  y += 1; doc.line(4, y, 76, y); y += 3;
  row("Subtotal", rs(o.subtotal), 7);
  if (o.discount > 0) row("Discount", "-" + rs(o.discount), 7);
  row("Tax", rs(o.tax), 7);
  row("TOTAL", rs(o.total), 9, true);
  row(`Paid (${o.payment?.method ?? o.tender ?? "-"})`, o.paid ? rs(o.total) : "UNPAID", 7);
  y += 2;
  line("Thank you! Visit again.", 7);
  return doc.output("blob");
}

function reportPdf(d: EodData): Blob {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = 18;
  const L = (t: string, size = 11, bold = false) => {
    doc.setFontSize(size); doc.setFont("helvetica", bold ? "bold" : "normal");
    doc.text(t, 16, y); y += size * 0.5 + 2;
  };
  const R = (l: string, r: string) => {
    doc.setFontSize(11); doc.setFont("helvetica", "normal");
    doc.text(l, 16, y); doc.text(r, 194, y, { align: "right" }); y += 7;
  };
  L(d.storeName, 18, true);
  L(`End of Day Report — ${d.date}`, 13, true);
  y += 2;
  R("Orders", String(d.summary.orderCount));
  R("Total sales", rs(d.summary.sales));
  R("Tax collected", rs(d.summary.tax));
  R("Discounts", rs(d.summary.discount));
  y += 3; L("Payment mix", 12, true);
  for (const [m, v] of Object.entries(d.summary.byMethod)) R(m, rs(v));
  y += 3; L("Top sellers", 12, true);
  d.summary.topItems.forEach((it, i) => R(`${i + 1}. ${it.name}`, `${it.qty} · ${rs(it.revenue)}`));
  y += 6;
  doc.setFontSize(9); doc.setFont("helvetica", "italic");
  doc.text("Generated by CafePOS — keep this file as your permanent record (GST/audit).", 16, y);
  return doc.output("blob");
}

function ordersCsv(d: EodData): string {
  const head = ["Bill", "DateTime", "Customer", "Phone", "Items", "Subtotal", "Discount", "Tax", "Total", "Tender", "Paid", "Cashier"];
  const rows = d.orders.map((o) => [
    o.number,
    new Date(o.createdAt).toLocaleString(),
    o.customerName ?? "",
    o.customer?.phone ?? "",
    o.items.map((i) => `${i.qty}x ${i.name}`).join("; "),
    o.subtotal, o.discount, o.tax, o.total,
    o.payment?.method ?? o.tender ?? "",
    o.paid ? "Yes" : "No",
    o.cashier?.name ?? "",
  ].map((c) => `"${String(c).replace(/"/g, '""')}"`).join(","));
  return [head.join(","), ...rows].join("\r\n");
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

/**
 * One-click End-of-Day: pulls the day's data, builds a ZIP (report PDF + one invoice
 * PDF per bill, timestamped + named + a CSV), downloads it to this machine, then closes
 * the day in the cloud (saves the summary and purges detail past the retention window).
 */
export async function downloadEOD(date?: string): Promise<{ purgedOrders: number; orderCount: number }> {
  const { data } = await api.get("/eod/data", { params: date ? { date } : {} });
  const d = data as EodData;

  const zip = new JSZip();
  zip.file(`EOD-report-${d.date}.pdf`, reportPdf(d));
  zip.file(`orders-${d.date}.csv`, ordersCsv(d));
  const inv = zip.folder("invoices")!;
  for (const o of d.orders) {
    const dt = new Date(o.createdAt);
    const stamp = `${d.date.replace(/-/g, "")}-${String(dt.getHours()).padStart(2, "0")}${String(dt.getMinutes()).padStart(2, "0")}`;
    const who = clean(o.customerName ?? o.customer?.phone ?? "walkin");
    inv.file(`invoice_${o.number}_${who}_${stamp}.pdf`, invoicePdf(o, d.storeName));
  }
  const blob = await zip.generateAsync({ type: "blob" });
  triggerDownload(blob, `CafePOS_EOD_${d.storeName.replace(/[^a-zA-Z0-9]+/g, "-")}_${d.date}.zip`);

  // Close the day in the cloud (persist summary + purge old detail).
  const close = await api.post("/eod/close", null, { params: date ? { date } : {} });
  return { purgedOrders: close.data.purgedOrders ?? 0, orderCount: d.summary.orderCount };
}
